### ISSUE TITLE
infinite values for "grid_area" when creating SCRIP file from land ice mesh with "sphere_radius" attribute = 0

### ISSUE THREAD

**Issue by stephenprice** [MPAS-Dev/MPAS-Tools#132]
@douglasjacobsen and @matthewhoffman, I've come across a problem with some recent updates to the "create_SCRIP_file_from_MPAS_mesh.py" script. 

The change on line 69 (line 70 in new code) here https://github.com/MPAS-Dev/MPAS-Tools/commit/ce11b3d1597ffbbbae844dd14f26563d47a081f3 causes division by zero with land ice meshes where the "sphere_radius" attribute is set to 0 (previously, sphere radius value was hard coded into this python script). In turn, this leads to inf values for the "grid_area" field in the resulting SCRIP file.

Should the land ice folks be altering their meshes so that this value is defined correctly even when using planar meshes?

**Comment by xylar** [comment]
@stephenprice and @matthewhoffman, has this been resolved?

**Comment by stephenprice** [comment]
Hi @xylar. This is an old one and I don't remember the details. @matthewhoffman, I can test this w/ a new mesh (but if you happen to know it's already fixed I won't waste me time).

**Comment by xylar** [comment]
@stephenprice, yes, I was going through old issues on this repo just to make sure they're still relevant.

**Comment by douglasjacobsen** [comment]
@xylar and @stephenprice This *should* still be an issue, for any older mesh that doesn't have sphere_radius defined, or if it's set to 0.

Probably just need some error handling here, and if sphere_radius is 0, just set it to 1. Or something like that...
https://github.com/MPAS-Dev/MPAS-Tools/blob/master/mesh_tools/create_SCRIP_files/create_SCRIP_file_from_MPAS_mesh.py#L54

**Comment by stephenprice** [comment]
Thanks @douglasjacobsen. Newer (planar) meshes still appear to have sphere_radius set to 0, e.g. from a recent hi-res. Ant. mesh:

`// global attributes:`
`:on_a_sphere = "NO              " ;`
`:sphere_radius = 0. ;`

I'll see if I can add some error handling as you suggest.
