### ISSUE TITLE
Improve MaskCreator when dealing with transects

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Tools#143]
This issue is intended to scope out ideas on how to create transect masks that zig-zag less and instead follow more closely a line of constant latitude (or longitude). Therefore, the discussion will be more relevant for zonal or meridional transects.

Discussion started in issue MPAS-Dev/geometric_features#69.

**Comment by xylar** [comment]
This is partly addressed by #399.  That PR does much better intersection of transects and cells without any zig-zagging.  

What is not handled by #399 is `edgeSign` so I'm leaving this open until that gets added.

**Comment by xylar** [comment]
Addressed by #404
