### ISSUE TITLE
Something still not right in moc_southern_boundary_extractor

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Tools#164]
Things seemed to work fine with lower resolution meshes, but I have used the Atlantic_MOC transect/region generated by the extractor with the 18to6, and the resulting MOC streamfunction is weird.
Here are results with the old transect:
![mocatlantic_gmpas-iaf_orrs18to6v3_years0011-0011](https://cloud.githubusercontent.com/assets/8237579/25704667/a6b7b176-3097-11e7-84db-b58264a26e07.png)

And here they are with the new transect:
![mocatlantic_moc_gmpas-iaf_orrs18to6v3_years0011-0011](https://cloud.githubusercontent.com/assets/8237579/25704673/ab1a5f52-3097-11e7-9945-d113dac3cc91.png)

**Comment by xylar** [comment]
Addressed in #181
