### ISSUE TITLE
ImportError: No module named builtins when running paraview_vtk_field_extractor.py

### ISSUE THREAD

**Issue by caozd999** [MPAS-Dev/MPAS-Tools#233]
I got the ImportError message "No module named builtins" when running the following command
           python paraview_vtk_field_extractor.py -h

Does anyone know how to fix this issue?

**Comment by xylar** [comment]
@caozd999, could you tell us more about you python environment?  Which version are you using? What packages are installed?

**Comment by xylar** [comment]
I think the solution is that you need to install the `futures` package.

**Comment by caozd999** [comment]
Hi @xylar, I am running it on gr-fe, and the python version is 2.7.14. Cannot install the `future` package from my side.

**Comment by xylar** [comment]
@caozd999, you won't be able to use the paraview extractor with the default python environment on LANL IC.  Try loading the `e3sm-unified` python environment.  You can source the file `/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_e3sm_unified.sh` (or `.csh` if you use csh or tcsh as your shell).

**Comment by caozd999** [comment]
@xylar Thank you Xylar! Problem solved by `module remove python` and then `module load e3sm-unified`.

**Comment by xylar** [comment]
Glad it worked! However, I would strongly discourage you from using the e3sm-unified module, which is for an outdated version. The environment is only partially loaded by a module file, leading to potential problems. If the path I provided above to the file to be sourced doesn't work for some reason, let me know.

**Comment by xylar** [comment]
Yeah, I deleted the module file.  Like I said, I don't think it's a good idea to use it.

**Comment by caozd999** [comment]
:'( OK. So now we do `source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/load_latest_e3sm_unified.sh` if we want to run the paraview_vtk_fied_extractor.py. Is that correct?

**Comment by xylar** [comment]
Yes, there isn't a safe way to load conda environments with a module file (at least not that I'm aware of) for the most recent versions of conda.  As I said, there's a risk that environment variables don't get set and packages don't work.
