### ISSUE TITLE
Support for files with Time dimension but without xtime variable in VTK extractor

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Tools#235]
@bradyrx as requested a way to handle a file without an `xtime` or equivalent time variable.  Currently the VTK extractor can only pull out the first time slice of such a file with `--ignore_time`.

**Comment by bradyrx** [comment]
The use case here would be concatenating a bunch of monthly output files into one `.nc` file, which has a `Time` dimension, but no `xtime` variable.

**Comment by xylar** [comment]
@bradyrx, is there a reason not to concatinate the `xtime` dimension when you're concatinating the monthly files?  They should have `xtime_startMonthly` and `xtime_endMonthly` in the monthly files, and it would be best to preserve these if possible.

**Comment by bradyrx** [comment]
@xylar, I'm working with trimmed down files of a long high-res run for space preservation. I realize now that when @maltrud and I decided on the variables to retain, we forgot to add `xtime` to the ncks command. So I guess this is a fringe use case and typically shouldn't be an issue.

**Comment by xylar** [comment]
Okay, that's what I was assuming.  Obviously, it would be good to extract `xtime` in the future but we do seem to end up with files that are missing `xtime` from time to time so it makes sense to have a workaround even if it's kind of an edge case.

If MPAS had a proper, CF-compliant `time` dimension and coordinate, we wouldn't have this problem...
