### ISSUE TITLE
Is the 'adds_coarse_to_fine_grid_preprocessing_interpolation' branch needed?

### ISSUE THREAD

**Issue by mgduda** [MPAS-Dev/MPAS-Tools#240]
I just noticed there is a branch, `adds_coarse_to_fine_grid_preprocessing_interpolation`, in the main `MPAS-Tools` repository that was last modified sometime in 2017. Is this branch still needed? If it has been merged or is no longer in use, could we delete it?

**Comment by xylar** [comment]
@pwolfram, this seems like your style of branch naming and I believe the first few commits are yours.  Could you have pushed this to MPAS-Dev/MPAS-Tools by mistake?

**Comment by pwolfram** [comment]
@xylar, see https://github.com/MPAS-Dev/MPAS-Tools/pull/152 and I've gisted to https://gist.github.com/0f2b83c3dbf492ef06512e95c8d11169

**Comment by pwolfram** [comment]
I think we can close, please let me know if you disagree @xylar.
