### ISSUE TITLE
COMPASS mesh generation clean up

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Tools#263]
We need to make sure we have unique scripts, not scripts in multiple places, e.g.:

https://github.com/MPAS-Dev/MPAS-Tools/blob/master/mesh_tools/triangle_jigsaw_to_netcdf/inject_bathymetry.py

https://github.com/MPAS-Dev/MPAS-Model/blob/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS/inject_bathymetry.py

**Comment by pwolfram** [comment]
cc @sbrus89

**Comment by xylar** [comment]
@sbrus89, could you verify which of the following 2 directories contains the version of the following files that are actually used in compass?  I suspect it's the MPAS-Model version, but need you to let me know for sure.  I'll remove whichever is the redundant copy.

Directories:
* https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS
* https://github.com/MPAS-Dev/MPAS-Tools/tree/master/mesh_tools/triangle_jigsaw_to_netcdf

The redundant files:
* build_mesh.py/build_mesh.sh
* inject_bathymetry.py
* mpas_to_triangle.py
* open_msh.py
* triangle_jigsaw_to_netcdf.py

It *seems* like the whole `trangle_jigsaw_to_netcdf` directory in MPAS-Tools should be deleted.
