### ISSUE TITLE
paraview_vtk_field_extractor produces extra characters after xtime

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Tools#317]
I’m using e3sm_unified_1.3.0 on cori, paraview_vtk_field_extractor.py. In the file
`vtk_output/time_series/fieldsOnCells.0.vtp`
line 5 is:
```
      4 <xtime>
      5 0001-01-11_00:00:00^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
      6 </xtime>
```
The `^@` are some crazy characters vim doesn’t understand. I can delete those by hand, or use   `-x none`. But we want to avoid the creation of the `^@` characters. 

This results in paraview producing an error about invalid xml file format, and not able to open the file.

**Comment by xylar** [comment]
closed via #318

**Comment by pwolfram** [comment]
Thanks  @xylar  and @mark-petersen, had this issue myself recently.

**Comment by xylar** [comment]
These same issues are wreaking havoc in MPAS-Analysis.  My project for the evening.  Stupid PIO2!
