### ISSUE TITLE
Switch signed distance functions from rasterio to inpoly

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Tools#415]
The `rasterio` package is very complicated, with a lot of dependencies.  It is unnecessarily complicated for what we need it for, making a mask from some polygons.  @dengwirda has written a much simpler and likely equally (or perhaps more) performant tool, [inpoly](https://github.com/dengwirda/inpoly-python), that we should use instead.

This would likely resolve some dependency problems that `rasterio` has introduced because it is not able to use the latest `proj` library (8.0.0).

**Comment by xylar** [comment]
`inpoly` may also be useful in speeding up other mask creation operations in `mpas_tools`.

**Comment by dengwirda** [comment]
@xylar, just confirming that (at least with standard `cpython`) the `inpoly` conda package looks to be correctly delegating to the fast `cython` kernel, so all should be ready to go here.

**Comment by xylar** [comment]
This was done in https://github.com/MPAS-Dev/MPAS-Tools/pull/420
