### ISSUE TITLE
Add MpasMaskCreator back (temporarily)

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Tools#533]
The old `MpasMaskCreator` C++ tool was superseded by the new python tool in #514. For transect masks, the former does something that no other tool does at the moment though, and that is the ordering of the transect elements (say, edges) starting from the transect start point and ending with the transect end point. That is important for plotting routines that rely on transect edge masks to plot vertical sections (x vs z plots).
Until we have a plotting routine for cross-transect velocities that does not rely on the edge mask, it would be good to add the old C++ tool back.

**Comment by xylar** [comment]
Thanks @milenaveneziani!

**Comment by milenaveneziani** [comment]
Thanks @xylar. That was fast!

**Comment by xylar** [comment]
Sure, no problem!
